### ISSUE TITLE
The value NaN for parameter MetricData.member.1.Value is invalid.

### ISSUE THREAD

**Issue by gvasquez95** [aws-samples/resource-utilization#20]
Ref log in Step Function `StoreRegionalUtilization` step

`{
  "errorType": "InvalidParameterValueException",
  "errorMessage": "The value NaN for parameter MetricData.member.1.Value is invalid.",
  "trace": [
    "InvalidParameterValueException: The value NaN for parameter MetricData.member.1.Value is invalid.",
    "    at deserializeAws_queryInvalidParameterValueExceptionResponse (/var/runtime/node_modules/@aws-sdk/client-cloudwatch/dist-cjs/protocols/Aws_query.js:2000:23)",
    "    at deserializeAws_queryPutMetricDataCommandError (/var/runtime/node_modules/@aws-sdk/client-cloudwatch/dist-cjs/protocols/Aws_query.js:1674:25)",
    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "    at async /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24",
    "    at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20",
    "    at async StandardRetryStrategy.retry (/var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)",
    "    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22",
    "    at async putMetric (file:///var/task/index.mjs:33:3)",
    "    at async Runtime.handler (file:///var/task/index.mjs:52:3)"
  ]
}`

**Comment by gvasquez95** [comment]
`null` value found at `GetInstanceUtilization` lambda output:

`{
  "utilization": null,
  "vcpus": 2
}`

**Comment by gvasquez95** [comment]
root cause:

1. wrong parameter for region at CloudWatch client instantiation
2. missing result/return value assignment
